### ISSUE TITLE
Design UI

### ISSUE THREAD

**Issue by mike-webster** [mike-webster/30-days-of-code-072019#3]
## Description
We need to come up with some designs that will work.

## Open Questions
- [ ] What are the appropriate Android UI elements to use?

## Interfaces
- [ ] Display Saved Alarms
    - List of alarms user has saved
    - Edit and Delete buttons
- [ ] Edit/Add Alarm
    - Allow user to choose time and days
    - Save, cancel
    - If edit - load the days and time
- [ ] Alarm going off
    - Allow user to snooze or stop alarm

## Future Enhancements
- Customize:
    - Alarm Sound
    - Alarm Vibration
    - Clock Display 12/24
    - Snooze Default Time (10 minutes)

## Blocked By

**Comment by mike-webster** [comment]
Break this out into appropriate cards when the work begins

**Comment by mike-webster** [comment]
![image](https://user-images.githubusercontent.com/25595930/60310325-ebbf6f80-9917-11e9-921a-870d5362e280.png)
Notes:
- Days will be "highlighted" if alarm is active
- Those things at the end are the edit and delete buttons, ideally - they'll look better than I drew them 😆

**Comment by mike-webster** [comment]
![image](https://user-images.githubusercontent.com/25595930/60310356-22958580-9918-11e9-8556-e21cf0605395.png)
Notes:
- Time inputs, sliders?
    - Maximums: Hour - 12; Minute - 59
    - Minimums: Hour - 1; Minute - 0
- AM/PM
    - No idea what inputs there are available, it's a boolean. Clicking should switch value.
- Days
    - Not sure which input to use, bool - but active/inactive
    - "active" state should be "highlighted"
- Cancel
    - If modal - close modal.
    - If no modal - return to list of alarms
- Save
    - persist alarm
    - if modal - close modal
    - if no modal - return to list of alarms

**Comment by mike-webster** [comment]
![image](https://user-images.githubusercontent.com/25595930/60310579-2f66a900-9919-11e9-9f5f-b145aedb5cb4.png)
Notes:
- Not sure what the content should be
- Background should be all white
- Clicking "alarm":
    - stops sound
    - opens snooze menu

Open Questions:
- Can we turn the brightness up gradually? future enhancement?

**Comment by mike-webster** [comment]
![image](https://user-images.githubusercontent.com/25595930/60310681-95533080-9919-11e9-810c-97ffa31a9b3a.png)
Notes:
- Make the input a slider so user can choose
    - Default value to 10
    - Max: 59; Min: 1
- Snooze
    - Sets a timer for the number of minutes the user chose
- Nah, I'm up
    - Brings user to list of alarms

Open Questions:
- Should this just be a modal too?

**Comment by mike-webster** [comment]
relevant to [modals](https://developer.android.com/guide/topics/ui/dialogs.html)

**Comment by mike-webster** [comment]
use for [time selection](https://developer.android.com/reference/android/widget/TimePicker)

**Comment by mike-webster** [comment]
Might have to just use these for the [days](https://www.tutorialspoint.com/android/android_checkbox_control.htm)

**Comment by mike-webster** [comment]
Well shit... here's a full tutorial in case I get stuck: https://javapapers.com/android/android-alarm-clock-tutorial/

I'm gonna try to not use it though.
