### ISSUE TITLE
Implement JWTs and Auth

### ISSUE THREAD

**Issue by mike-webster** [mike-webster/30-days-of-code-072019#32]
## Description
I just realized that authentication will be blocking most of the endpoints.  This needs to be done early on.

## Tasks
- [ ] Add Auth project
- [ ] Generate secrets
- [ ] Implement custom JWTs
    - Payload
        - user_id
        - role
        - created_at
        - expires_at
- [ ] Expose method for creating new token
- [ ] Expose method for validating token

**Comment by mike-webster** [comment]
I got caught up on getting the tests to pass for the create method I wrote.  The stupid things are telling me the db isn't set up correctly, so I got wayyyy sidetracked trying to get the db to work.
